apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ex2-run-pipeline
  namespace: ex2
spec:
  pipelineRef:
    name: ex2-pipeline

  params:
    - name: message
      value: "Once upon a time in Hollywood"

  workspaces:
    - name: ex2-workspace # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 10Mi
