apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-pipeline-run
  generateName: git-clone-pipeline-run-
spec:
  pipelineRef:
    name: git-clone-pipeline
  workspaces:
    - name: mr-test-ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Mi
