apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronprints.crd.tekton
  namespace: tekton-pipelines
spec:
  group: crd.tekton
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  description: The cron spec defining the interval the print is run
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                text:
                  description: Text to be printed
                  type: string
      additionalPrinterColumns:
      - name: Spec
        type: string
        description: The cron spec defining the interval a cronPrint is run
        jsonPath: .spec.cronSpec
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      - name: Suspend
        type: boolean
        jsonPath: .status.suspend
      - name: Last Scheduled
        type: date
        jsonPath: .status.lastScheduled
  scope: Namespaced
  names:
    plural: cronprints
    singular: cronprint
    kind: CronPrint
    shortNames:
      - cp



