apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: write-to-file
  annotations:
    description: |
      A simple task that writes a message to a file
  namespace: ex2-clusterwide
      
spec:
  params:
    - name: message
      type: string
      description: An input string
    - name: path
      type: string
      description: >
        Relative path to create within the workspace.

  workspaces:
    - name: ex1-workspace
      description: Workspace onto which the file is written.
      
  steps:
    - name: write-file
      image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:3685c58885771d2ea14608caeab6a4c3949b973588c29ce91f462b486ee1be25
      workingDir: $(workspaces.ex1-workspace.path)
      env:
        - name: PARAM_PATH
          value: $(params.path)
        - name: PARAM_MSG
          value: $(params.message)
      timeout: 60s
      script: |
        #!/usr/bin/env bash
        DIRNAME=$(dirname "${PARAM_PATH}")
        mkdir -p "$DIRNAME"
        printf '%s' "${PARAM_MSG}" | tee "./${PARAM_PATH}"

